---
services:
  opencloud:
    image: docker.io/opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    ports:
      - 9200:9200
    environment:
      OC_URL: https://your.public.domain # Prepare an HTTPS URL before setting up this service.
      PROXY_TLS: "false"
      OC_INSECURE: "false"
      IDM_ADMIN_PASSWORD: "password"
      OC_PASSWORD_POLICY_DISABLED: "true"
    volumes:
      - ./config:/etc/opencloud
      - ./lib:/var/lib/opencloud
    restart: always
